# **Liner Algebra**
In Pytorch, variables are stored in tensors.

In [1]:
import torch

In [2]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

print('x + y = ', x + y)
print('x * y = ', x * y)
print('x / y = ', x / y)
print('x ** y = ', torch.pow(x,y))

x + y =  tensor([5.])
x * y =  tensor([6.])
x / y =  tensor([1.5000])
x ** y =  tensor([9.])


In Pytorch, we can convert any tensors to a Python flooat by calling its *item()* method. (which
this is typically a bad idea.)

In [3]:
x.item()

3.0

# **Vectors**
Vectors are e.g. [1.0, 3.0, 4.0, 2.0] . We use 1D tensors.


In [4]:
x = torch.arange(5)
print('x = ', x)

x = torch.tensor([1.0, 3.0, 4.0, 2.0])
print('x = ', x)

x[3]

x =  tensor([0, 1, 2, 3, 4])
x =  tensor([1., 3., 4., 2.])


tensor(2.)

# **Length, dimensionality and shape**

The length of a vector is commonly called its dimension. We can access a ventor tensor's length via its *.shape* attribute. The shape is a tuple that lists the dimensionality along each of its axes.

In [5]:
x.shape

torch.Size([4])

# **Matrices**

In [6]:
print(torch.arange(10))
A = torch.arange(20).reshape((5,4))
print(A)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


Element $a_{ij}$ of matrix $\mathbf{A}$ by specifying $i$th row and $j$th column.
Matrix transpose can be achieved through *.T* atrribute. 

In [7]:
i, j = 1, 3
print('a_ij:', A[i,j].item())
print('Matrix transpose:', A.T)

a_ij: 7
Matrix transpose: tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


# **Tensors**

A tensor is a generalization of vectors and matrices to potentially higher dimensions. You can think it as a n-dimensional s of base datatypes.

For example, when working with images, a model input is usually represented as the axes that correspond to [batch, RGB color channels, height, width].

In [8]:
X = torch.arange(24).reshape((2, 3, 4))
print('X.shape =', X.shape)
print('X =', X)

X.shape = torch.Size([2, 3, 4])
X = tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


# **Basic properties of tensor arithmetic**

Given two tensors $X$, $Y$ with the same shape, $\alpha X+Y$ has the same shape.

In [9]:
a = 2
x = torch.ones(3)
y = torch.zeros(3)
print(x.shape)
print(y.shape)
print((a * x).shape)
print((a * x + y).shape)

torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])


# **Sums and means**



In [10]:
print(x)
print('Sum of vector', torch.sum(x))
print(A)
print('Sum of matrix', torch.sum(A))

tensor([1., 1., 1.])
Sum of vector tensor(3.)
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
Sum of matrix tensor(190)


For the sum of matrices, you can also specify which dimension to be summed.

In [11]:
print(A)
print('Sum over rows of matrix', torch.sum(A, dim=0))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
Sum over rows of matrix tensor([40, 45, 50, 55])


A related quantity is the *mean*

In [12]:
print(torch.mean(A.float()))
print(torch.sum(A.float()) / torch.numel(A))

tensor(9.5000)
tensor(9.5000)


Similary, you can specify which dimension to calculate the mean.

In [13]:
print(torch.mean(A.float(), dim=0))

tensor([ 8.,  9., 10., 11.])


# **Dot productions**

Given two vectors $\mathbf{u}$ and $\mathbf{v}$, the dot product $\mathbf{u}^T\mathbf{v}$ is a sum over the products of the corresponding elements:$\mathbf{u}^T\mathbf{v} = \sum_{i=1}^d u_i\cdot v_i$.

Both *torch.matmul* and *torch.dot* are okay to 1-dimensional tesnsor (vectors).

In [14]:
x = torch.arange(4).float()
y = torch.ones(4).float()
print(x, y, torch.matmul(x, y))
print(x, y, torch.dot(x, y))

tensor([0., 1., 2., 3.]) tensor([1., 1., 1., 1.]) tensor(6.)
tensor([0., 1., 2., 3.]) tensor([1., 1., 1., 1.]) tensor(6.)


Actually, for 1-dimensional tensors, *torch.matmul* will always return the dot product (scalar). And for 2-dimensional tensors, the matrix-matrix product is returned.

In [15]:
print(torch.matmul(x.T, y.T))
print(torch.matmul(x.reshape((4,1)), y.reshape((1,4))))

tensor(6.)
tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])


Note that the dot product of two vectors is  equivalent to performing an element-wise multiplication and then a sum:

In [16]:
torch.sum(x * y)

tensor(6.)

# **Matrix-vector products**

Simimarly, we use *torch.matmul*.

In [17]:
torch.matmul(A.float(), x.float())

tensor([ 14.,  38.,  62.,  86., 110.])

# **Matrix-matrix multiplication**

We can think of the matrix-matrix multiplication as simply performing $m$ matrix-vector products and stitching the results together.

Again, we can use *torch.matmul* to achieve this operation.

In [18]:
B = torch.ones((4, 3))
torch.matmul(A.float(), B.float())

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

# **Norms**

$\ell_2$ norm:

In [19]:
torch.norm(x)

tensor(3.7417)

$\ell_1$ norm:

In [20]:
torch.sum(torch.abs(x))

tensor(6.)