# ***tensors* Tutorial**
The simplest object we can create is a vector. 

In [1]:
import torch

x = torch.arange(12)
print (x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


We can ge the *tensor* shape through its *shape* attribute or *size()* function

In [2]:
x.shape

torch.Size([12])

In [3]:
x.size()

torch.Size([12])

The reshape function change the shape of the vector $x$ to a matrix of 3 rows and 4 columns.

In [4]:
x = x.reshape((3, 4))
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


Call *empty* to allocate some memory for a tensor filled with uninitialized data

In [5]:
torch.empty(2, 3)

tensor([[1.6620e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

Usually, we initialize a tensor with all zeros. For example, an all zero matrix at size (2, 3, 4)

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

We can also intialize a tensor with all ones.

In [7]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

We can also specify the value of each element to initialize a tensor (But it is rarely done bucause usually we may either have a quite large tensor to feed the model or we want it to be initialized with a certain distribution).

In [8]:
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(y)

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


In some cases, we need to randomly generate the value of each element. This is especially common when we intend to use the array as a parameter in a neural network.

The following code creates a tensor with the shape of (3,4), and each elements of it is randomly sampled in a normal distribution with zero mean and unit variance.

In [9]:
torch.normal(mean=0.0, std=1.0, size=(3, 4))

tensor([[ 0.1873, -0.3825,  1.8787, -0.4430],
        [ 0.5780,  2.0361, -0.2708, -1.5990],
        [-0.2644, -0.7748, -2.1668,  0.7127]])

# **Operations**

In [10]:
x = torch.tensor([1, 2, 4, 8], dtype=torch.float32)
y = torch.ones_like(x) * 2
print('x = ', x)
print('x + y = ', x + y)
print('x - y = ', x - y)
print('x * y = ', x * y)
print('x / y = ', x / y)
print('Element-wise exponentation: ', x.exp())

x =  tensor([1., 2., 4., 8.])
x + y =  tensor([ 3.,  4.,  6., 10.])
x - y =  tensor([-1.,  0.,  2.,  6.])
x * y =  tensor([ 2.,  4.,  8., 16.])
x / y =  tensor([0.5000, 1.0000, 2.0000, 4.0000])
Element-wise exponentation:  tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


We can also concatenate tensors at the dimension we want. 

In [11]:
x = torch.arange(12).reshape((3,4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((x, y), dim=0))
print(torch.cat((x, y), dim=1))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])
tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])


Like in Numpy, we can construct binary tensors by a logical statement.

In [12]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

Personally, I don't like broadcast mechanism. I'd rather use *torch.repeat* to modify the tensor to desired shape and then add two tensors.

In [13]:
a = torch.arange(3, dtype=torch.float32).reshape((3, 1))
b = torch.arange(2, dtype=torch.float32).reshape((1, 2))

print('a, b: ', a, b)

print('Boardcast mechanism of a+b shoule be equvalent to: \n', a.repeat(1, 2) + b.repeat(3,1))

a, b:  tensor([[0.],
        [1.],
        [2.]]) tensor([[0., 1.]])
Boardcast mechanism of a+b shoule be equvalent to: 
 tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])


# **Indexing and Slicing**

Indexing and Slicing in Pytorch tensors are the same as what we do in Python.

# **Transformation between Pytorch tensors and Numpy array**

Note that according to PyTorch document, **UNLIKE** MxNet, the torch Tensor and numpy array will **SHARE** their underlying memory locations, and changing one will change the other.

In [14]:
import numpy as np

a = x.numpy()
print(type(a))
b = torch.tensor(a)
print(type(b))

t = torch.ones((3, 2))
n = t.numpy()
print("Before change tensor value: {} \n {}.".format(t, n))

t[0,0] = 100

print("After change tensor value: {} \n {}.\n\n".format(t, n))

!pip install mxnet
import mxnet as mx
from mxnet import nd
mx_nd = nd.ones((3,2))
mx_n = mx_nd.asnumpy()

print("Before change NDArray value: {} \n {}.".format(mx_nd, mx_n))

mx_nd[0,0] = 100

print("After change NDArray value: {} \n {}.".format(mx_nd, mx_n))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
Before change tensor value: tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) 
 [[1. 1.]
 [1. 1.]
 [1. 1.]].
After change tensor value: tensor([[100.,   1.],
        [  1.,   1.],
        [  1.,   1.]]) 
 [[100.   1.]
 [  1.   1.]
 [  1.   1.]].


Before change NDArray value: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
<NDArray 3x2 @cpu(0)> 
 [[1. 1.]
 [1. 1.]
 [1. 1.]].
After change NDArray value: 
[[100.   1.]
 [  1.   1.]
 [  1.   1.]]
<NDArray 3x2 @cpu(0)> 
 [[1. 1.]
 [1. 1.]
 [1. 1.]].
