# **Maximum Pooling and Average Pooling**

Pooling layers does not change the number of channels, it only downsamples the spatial infomation.

In [1]:
import torch

def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

We can construct the input array $X$ in the above diagram to validate the output of the twodimensional maximum pooling layer.

In [2]:
X = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]], dtype=torch.float32)
print(X)
print(pool2d(X, (2, 2)))

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[4., 5.],
        [7., 8.]])


## **Average Pooling**

In [3]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

## **Padding and Stride**

In [4]:
X = torch.arange(16).reshape((1, 1, 4, 4)).float()
print(X)

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])


By default the stride for a window of (3, 3) is (3, 3).

In [5]:
import torch.nn as nn
pool2d = nn.MaxPool2d(3)
# Because there are no model parameters in the pooling layer, we do not
# need to call the parameter initialization function.
pool2d(X) 

tensor([[[[10.]]]])

The stride and padding can be manually specied.

In [6]:
pool2d = nn.MaxPool2d(3, padding = 1, stride = 2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

Arbitrary window

In [7]:
pool2d = nn.MaxPool2d((2, 3), padding = (1, 1), stride = (2, 3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

## **Multiple Channels**
Pooling is applied per channel.

In [8]:
X = torch.cat((X, X + 1), dim=1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

As we can see, the number of output channels is still 2 after pooling.

In [9]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])