# **GPUs**

Note that in the Colab, you need to first change your runtime type to 'GPU':

Runtime--> Change runtime type--> Hardware accelerator--> GPU


In [1]:
!nvidia-smi

Fri Sep 25 23:52:46 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8     9W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Computing Devices


In [2]:
import torch

torch.device('cpu'), torch.cuda.device('cuda')

(device(type='cpu'), <torch.cuda.device at 0x7f6565017278>)

## **Tensors and GPUs**


In [3]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

### **Storage on the GPU**


In [4]:
x = torch.ones((2, 3)).cuda(0)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

**Create on the second GPU:**

You can run the following code on devices with multiple GPUs to store the tensor on a different GPU.

In [ ]:
y = torch.randn(size=(2, 3)).cuda(1)
y

## Pytorch and GPUs

In [5]:
import torch.nn as nn
net = nn.Sequential(nn.Linear(3, 1))

net.cuda()

# When the input is an tensor on the GPU, 
# Pytorch will calculate the result on the same GPU.
print(net(x))
net[0].weight.data

tensor([[-0.4090],
        [-0.4090]], device='cuda:0', grad_fn=<AddmmBackward>)


tensor([[-0.0470, -0.5324,  0.4903]], device='cuda:0')