# **File I/O**


## **Save & Load Tensor**


In [1]:
import torch
import torch.nn as nn

x=torch.arange(4)
torch.save(x,"x-file")
x2 = torch.load("x-file")
print(x2)

tensor([0, 1, 2, 3])


### Save & Load a List of Arrays 

In [2]:
y = torch.zeros(4)
torch.save([x, y], 'xy-files')
x2, y2 = torch.load('xy-files')
print(x2, y2)

tensor([0, 1, 2, 3]) tensor([0., 0., 0., 0.])


### Save & Load a Dictionary of Arrays

In [3]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

## **PyTorch Model Parameters**

In [4]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
        self.relu = nn.ReLU()

    def forward(self, x):
        return self.output(self.relu(self.hidden(x)))

net = MLP()
x = torch.randn(size=(2, 20))
y = net(x)

### Save 

In [5]:
torch.save(net.state_dict(), 'mlp.params')

## Load 

In [6]:
clone = MLP()
clone.load_state_dict(torch.load("mlp.params"))

yclone = clone(x)
yclone == y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])